### ISSUE TITLE
Move sklearn to end of requirements.txt

### ISSUE THREAD

**Issue by geneorama** [potash/drain#56]
* drain version: Installed 2017-11-07
* Python version: 2.7
* Operating System: Old CentOS

### Description

Install requirements.txt

### What I Did

Installed each requirement one at a time, but did `sklearn` last

**Comment by potash** [comment]
@geneorama what does this fix? is it still necessary in light of the success you had last week?

**Comment by geneorama** [comment]
If python installs the dependencies in the order that they are presented, I would move `sklearn` to the end of the `requirements.txt`.  

I think that was the main key to how we got the requirements installed, but I'm not 100% sure that it wasn't something else.

**Comment by potash** [comment]
Changed in  af5bbec
